projects:
  client:
    schemaPath: src/generated/server.graphql
    extensions:
      endpoints:
        default: ${env:ENDPOINT}
      generate-fragments:
        output: src/generated/fragments.ts
        generator: js
