projects:
  server:
    schemaPath: src/generated/server.graphql
  client:
    schemaPath: src/generated/merged.graphql
    extensions:
      generate-fragments:
        output: src/generated/fragments.ts
        generator: js
