projects:
  server:
    schemaPath: packages/server/src/generated/server.graphql
    projectName: server
    extensions:
      endpoints:
        default: 'http://localhost:4000'
      override:
        - schema: packages/server/src/schema/schema.graphql
          overrides: packages/server/src/schema/overrides/overrides.graphql
          output: packages/server/src/generated/server.graphql
      codegen:
        - generator: graphql-binding
          language: typescript
          input: packages/server/src/schema/schema.ts
          output:
            binding: packages/server/src/generated/server.ts
  db-auth:
    schemaPath: packages/server/src/generated/authPrisma.graphql
    projectName: db-auth
    extensions:
      prisma: packages/db-auth/prisma.yml
      codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: packages/server/src/generated/authPrisma.ts
  db-resc:
    schemaPath: packages/server/src/generated/rescPrisma.graphql
    projectName: db-resc
    extensions:
      prisma: packages/db-resc/prisma.yml
      codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: packages/server/src/generated/rescPrisma.ts
