export { CandidateView } from './CandidateView'
export { DashboardView } from './DashboardView'
export { AuthView } from './AuthView'
export { ApplicationsView } from './ApplicationsView'
export { TestView } from './TestView'
