projects:
  app:
    schemaPath: src/generated/app.graphql
    projectName: app
    extensions:
      endpoints:
        default: 'http://localhost:4000'
      override:
        - schema: src/schema/schema.graphql
          overrides: src/schema/overrides/overrides.graphql
          output: src/generated/app.graphql
      codegen:
        - generator: graphql-binding
          language: typescript
          input: src/schema/schema.ts
          output:
            binding: src/generated/app.ts

  database:
    schemaPath: src/generated/prisma.graphql
    projectName: database
    extensions:
      prisma: database/prisma.yml
      codegen:
        - generator: prisma-binding
          language: typescript
          input: src/generated/prisma.graphql
          output:
            binding: src/generated/prisma.ts
