projects:
  app:
    schemaPath: src/schema/schema.graphql
    includes: ['**/*.graphql']
    extensions:
      endpoints:
        default: 'http://localhost:4000'
      codegen:
        - generator: graphql-binding
          language: typescript
          input: src/schema/schema.ts
          output:
            binding: src/generated/app.ts

  database:
    schemaPath: src/generated/prisma.graphql
    includes: ['**/*.graphql']
    extensions:
      prisma: database/prisma.yml
      codegen:
        - generator: prisma-binding
          language: typescript
          input: src/generated/prisma.graphql
          output:
            binding: src/generated/prisma.ts
