projects:
  server:
    schemaPath: src/generated/server.graphql
    projectName: server
    extensions:
      endpoints:
        default: 'http://localhost:4000'
  database:
    schemaPath: src/generated/prisma.graphql
    projectName: database
    extensions:
      prisma: database/prisma.yml
      codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: src/generated/prisma.ts
