projects:
  server:
    schemaPath: src/generated/server.graphql
    projectName: server
    extensions:
      endpoints:
        default: 'http://localhost:4000'
      override:
        - schema: src/schema/schema.graphql
          overrides: src/schema/overrides/overrides.graphql
          output: src/generated/server.graphql
      codegen:
        - generator: graphql-binding
          language: typescript
          input: src/schema/schema.ts
          output:
            binding: src/generated/server.ts
  database:
    schemaPath: src/generated/prisma.graphql
    projectName: database
    extensions:
      prisma: database/prisma.yml
      codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: src/generated/prisma.ts
