projects:
  server:
    schemaPath: src/generated/server.graphql
    extensions:
      endpoints:
        dev: https://vats-server.now.sh
  client:
    schemaPath: src/generated/server.graphql
    extensions:
      generate-fragments:
        output: src/generated/fragments.ts
        generator: js
